// flow-typed signature: 7e950130d5d492870000c3d8dcad9341
// flow-typed version: <<STUB>>/bootstrap-grid_v^2.0.1/flow_v0.37.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bootstrap-grid'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'bootstrap-grid' {
  declare module.exports: any;
}
