// flow-typed signature: b798121fc1ab1aaf19fd13b9b966701d
// flow-typed version: <<STUB>>/electron-config_v^0.2.1/flow_v0.37.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electron-config'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'electron-config' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'electron-config/index' {
  declare module.exports: $Exports<'electron-config'>;
}
declare module 'electron-config/index.js' {
  declare module.exports: $Exports<'electron-config'>;
}
