// flow-typed signature: 8ac5c25cda545484b3593cd98bd22097
// flow-typed version: <<STUB>>/jira-client_v^4.2.0/flow_v0.37.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jira-client'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'jira-client' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jira-client/lib/jira' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jira-client/lib/jira.js' {
  declare module.exports: $Exports<'jira-client/lib/jira'>;
}
